-- ============================================================
-- Wodflow — Core schema
-- Run this in your Supabase project's SQL editor, in order:
--   1. schema.sql            (this file)
--   2. judge-pin-login.sql
--   3. rls-policies.sql
-- ============================================================

create extension if not exists "pgcrypto";

-- ============================================================
-- EVENTS
-- Every domain table below carries event_id, even though Phase 1
-- runs a single active event — this costs nothing now and avoids a
-- migration if Wodflow ever runs a second organizer's event.
-- ============================================================
create table if not exists public.events (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  slug           text unique not null,
  start_date     date not null,
  end_date       date,
  venue_name     text,
  venue_address  text,
  contact_email  text,
  contact_phone  text,
  status         text not null default 'draft'
                   check (status in ('draft', 'published', 'live', 'archived')),
  waiver_text    text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ============================================================
-- PROFILES (extends auth.users) — organizer / judge / athlete
-- ============================================================
create table if not exists public.profiles (
  id               uuid primary key references auth.users(id) on delete cascade,
  full_name        text,
  email            text,
  phone            text,
  role             text not null default 'athlete'
                     check (role in ('organizer', 'judge', 'athlete')),
  -- Judge PIN login fields (populated by judge-pin-login.sql)
  pin_hash         text,
  pin_set          boolean not null default false,
  pin_attempts     int not null default 0,
  pin_locked_until timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, new.raw_user_meta_data->>'full_name', new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- DIVISIONS
-- ============================================================
create table if not exists public.divisions (
  id                     uuid primary key default gen_random_uuid(),
  event_id               uuid not null references public.events(id) on delete cascade,
  name                   text not null,              -- "RX Men", "Scaled Teams"
  team_size              int not null default 1 check (team_size >= 1),  -- 1 = individual
  price_early            numeric(10,2),
  price_normal           numeric(10,2) not null check (price_normal >= 0),
  price_late             numeric(10,2),
  early_bird_ends        date,
  late_starts            date,
  lane_count             int check (lane_count > 0),
  heat_duration_minutes  int check (heat_duration_minutes > 0),
  transition_minutes     int check (transition_minutes >= 0),
  workout_scoring_type   text not null default 'time'
                           check (workout_scoring_type in ('time', 'reps', 'load')),
  created_at             timestamptz not null default now()
);

-- ============================================================
-- REGISTRATIONS — one row per team (or individual). Payment
-- fields live directly on the row (nudgepay's proven pattern),
-- no separate payments table.
-- ============================================================
create table if not exists public.registrations (
  id                 uuid primary key default gen_random_uuid(),
  event_id           uuid not null references public.events(id) on delete cascade,
  division_id        uuid not null references public.divisions(id),
  team_name          text,                        -- null for individuals
  captain_profile_id uuid references public.profiles(id),
  registration_order bigint generated by default as identity,  -- fallback heat-seed order
  price_paid         numeric(10,2),
  payment_status     text not null default 'pending'
                       check (payment_status in ('pending', 'paid', 'waived', 'refunded')),
  pay_url            text,
  yoco_checkout_id   text,
  paid_at            timestamptz,
  paid_via           text,
  created_at         timestamptz not null default now()
);

-- ============================================================
-- REGISTRATION_ATHLETES — one row per teammate (every teammate
-- gets their own login later, not just the captain).
-- ============================================================
create table if not exists public.registration_athletes (
  id                 uuid primary key default gen_random_uuid(),
  registration_id    uuid not null references public.registrations(id) on delete cascade,
  profile_id         uuid references public.profiles(id),  -- null until they claim/sign up
  full_name          text not null,
  email              text not null,
  is_captain         boolean not null default false,
  waiver_signed_name text,
  waiver_signed_at   timestamptz,
  waiver_ip          text,
  created_at         timestamptz not null default now()
);

-- ============================================================
-- HEATS
-- ============================================================
create table if not exists public.heats (
  id            uuid primary key default gen_random_uuid(),
  event_id      uuid not null references public.events(id) on delete cascade,
  division_id   uuid not null references public.divisions(id) on delete cascade,
  heat_number   int not null check (heat_number > 0),
  start_time    timestamptz not null,
  end_time      timestamptz not null,
  status        text not null default 'scheduled'
                  check (status in ('scheduled', 'in_progress', 'completed')),
  unique (division_id, heat_number)
);

-- ============================================================
-- HEAT_ASSIGNMENTS
-- ============================================================
create table if not exists public.heat_assignments (
  id              uuid primary key default gen_random_uuid(),
  heat_id         uuid not null references public.heats(id) on delete cascade,
  registration_id uuid not null references public.registrations(id) on delete cascade,
  lane_number     int not null check (lane_number > 0),
  unique (heat_id, lane_number),
  unique (heat_id, registration_id)
);

-- ============================================================
-- JUDGE_ASSIGNMENTS — which judge is scoped to which heat.
-- ============================================================
create table if not exists public.judge_assignments (
  id         uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  heat_id    uuid not null references public.heats(id) on delete cascade,
  unique (profile_id, heat_id)
);

-- ============================================================
-- SCORES
-- Multiple rows per (heat_assignment_id, workout_id) are allowed —
-- a judge correcting a mis-entry submits a new row rather than
-- editing; the latest submitted_at per pair is authoritative
-- (see public_leaderboard view). client_submission_id is the
-- idempotency key for offline-first sync retries.
-- ============================================================
create table if not exists public.scores (
  id                    uuid primary key default gen_random_uuid(),
  heat_assignment_id    uuid not null references public.heat_assignments(id) on delete cascade,
  workout_id            text not null,
  value_raw             jsonb not null,   -- { time_seconds, reps, load_kg, no_rep }
  submitted_by          uuid references public.profiles(id),
  client_submission_id  uuid not null,
  submitted_at          timestamptz not null default now(),
  synced_at             timestamptz not null default now(),
  unique (heat_assignment_id, workout_id, client_submission_id)
);

-- ============================================================
-- Latest-score-wins view — leaderboard and organizer dashboards
-- read through this, never the raw scores table directly.
-- ============================================================
create or replace view public.latest_scores as
select distinct on (heat_assignment_id, workout_id)
  *
from public.scores
order by heat_assignment_id, workout_id, submitted_at desc;
